name: pwd
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  # flutter_platform_widgets: ^6.0.2


  # timezone: ^0.9.1

  flutter_bloc: ^8.1.6
  bloc_concurrency: ^0.2.5
  go_router: ^14.1.4
  equatable: ^2.0.5
  rxdart: ^0.27.7
  collection: ^1.18.0
  async: ^2.11.0
  path_provider: ^2.1.1
  # sqflite: ^2.3.0
  realm: ^3.0.0
  uuid: ^4.2.2
  crypto: ^3.0.3
  # encrypt: ^5.0.3

  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.2
  # clipboard: ^0.1.3

  shimmer: ^3.0.0

  dio: ^5.4.0
  retrofit: ^4.0.3
# Google:
  googleapis: ^13.1.0 
  google_sign_in: ^6.2.1
  firebase_core: ^3.0.0
  # googleapis_auth: ^1.4.1
  # firebase_core: ^2.24.2
  # firebase_auth: ^4.15.3

  meta: ^1.12.0
  json_annotation: ^4.9.0 
  json_serializable: ^6.8.0
  # realm_dart: ^1.6.1
  di_storage: ^1.0.0
  
  graphql: ^5.2.0-beta.8

  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  build_runner: ^2.4.9

  mocktail: ^1.0.2
  mockito: ^5.4.4
  # bloc_test: ^9.1.0
  retrofit_generator: ^8.0.5
  graphql_codegen: ^0.14.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
