# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:mac)

platform :mac do
  desc "Archive and distribute macOS app"
  #TODO - check if working
  lane :copy_mac_beta_app do
    sh("flutter", "build", "macos", "--release")
    gym(
      scheme: "Runner", 
      export_method: "development",
      output_directory: "~/Downloads", 
      output_name: "KeyMemo"
    )
  end
end
