# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:mac)

platform :mac do
  desc "Archive and distribute macOS app"
  #TODO - check if working
  lane :copy_mac_beta_app do
    Dir.chdir "../.." do
      sh("flutter", "clean")
      sh("flutter", "pub", "get")
      sh("dart run build_runner build --delete-conflicting-outputs")
      
      sh("flutter test --coverage")
      sh("flutter", "build", "macos", "--release")
    end
    gym(
      scheme: "Runner", 
      export_method: "development",
      output_directory: "~/Downloads", 
      output_name: "KeyMemo"
    )
    # https://github.com/advoryanskiy/fastlane-plugin-dmg?tab=readme-ov-file
    dmg(path: "~/Downloads/KeyMemo",             
        output_path: "/Downloads/KeyMemo.dmg")     
  end
end

platform :mac do
  desc "Archive and distribute macOS app"
  #TODO - check if working
  lane :app_to_dmg do
    # https://github.com/advoryanskiy/fastlane-plugin-dmg?tab=readme-ov-file
    dmg(path: "~/Downloads",             
        output_path: "~/Downloads/KeyMemo.dmg")     
  end
end