// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrenIqSClcMgi8oNsC5UfXhjAQxX8xX0E',
    appId: '1:133915072936:web:6de98fdd58422e526de59d',
    messagingSenderId: '133915072936',
    projectId: 'notesstorage-374314',
    authDomain: 'notesstorage-374314.firebaseapp.com',
    storageBucket: 'notesstorage-374314.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGHEO9uylCyIH7D_wuCqbPf78TeyDhfGQ',
    appId: '1:133915072936:android:ed2206bc3e2202fc6de59d',
    messagingSenderId: '133915072936',
    projectId: 'notesstorage-374314',
    storageBucket: 'notesstorage-374314.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlC3P1Zzo8P3C4U3VCCS78djEnHOCxEiU',
    appId: '1:133915072936:ios:6def13fcf993bb626de59d',
    messagingSenderId: '133915072936',
    projectId: 'notesstorage-374314',
    storageBucket: 'notesstorage-374314.appspot.com',
    androidClientId:
        '133915072936-m0khq3f3fhn8apdrcof9gv9bhsg50lf0.apps.googleusercontent.com',
    iosClientId:
        '133915072936-ap6bfbjng5qr9hcgvvs4h2fdcdssj5mc.apps.googleusercontent.com',
    iosBundleId: 'com.alekseii.popkov.pwd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlC3P1Zzo8P3C4U3VCCS78djEnHOCxEiU',
    appId: '1:133915072936:ios:6def13fcf993bb626de59d',
    messagingSenderId: '133915072936',
    projectId: 'notesstorage-374314',
    storageBucket: 'notesstorage-374314.appspot.com',
    androidClientId:
        '133915072936-m0khq3f3fhn8apdrcof9gv9bhsg50lf0.apps.googleusercontent.com',
    iosClientId:
        '133915072936-ap6bfbjng5qr9hcgvvs4h2fdcdssj5mc.apps.googleusercontent.com',
    iosBundleId: 'com.alekseii.popkov.pwd',
  );
}
